/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import java.awt.Color;
import BackEnd.MovimientoBackEnd;
import Entidad.MovimientoEntidad;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author facul
 */
public class GestionCaja extends javax.swing.JFrame {
    /**
     * Constructor: - Creates new form GestionClientes
     */
    public GestionCaja() {
        initComponents();
        initComponentsFacu();
        actualizarTabla();
        calcularSaldos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jr_ingreso = new javax.swing.JRadioButton();
        jr_efectivo = new javax.swing.JRadioButton();
        jt_monto = new javax.swing.JTextField();
        jt_especificacion = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jScrollPane_caja = new javax.swing.JScrollPane();
        jtable_caja = new javax.swing.JTable();
        jl_ingreso = new javax.swing.JLabel();
        jl_monto = new javax.swing.JLabel();
        jl_especificacion = new javax.swing.JLabel();
        jl_efectivo = new javax.swing.JLabel();
        jl_efectivoLabel = new javax.swing.JLabel();
        jl_Total = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        btn_borrarRegistros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Caja");
        setBackground(new java.awt.Color(49, 28, 28));
        setResizable(false);

        jl_titulo.setBackground(new java.awt.Color(49, 28, 28));
        jl_titulo.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 253, 118));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("CAJA");
        jl_titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jr_ingreso.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jr_ingreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jr_efectivo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jr_efectivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jt_monto.setBackground(new java.awt.Color(243, 243, 194));
        jt_monto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_monto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_monto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jt_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_montoKeyTyped(evt);
            }
        });

        jt_especificacion.setBackground(new java.awt.Color(243, 243, 194));
        jt_especificacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_especificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_especificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        btn_agregar.setBackground(new java.awt.Color(255, 253, 118));
        btn_agregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 253, 118));
        btn_eliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(255, 253, 118));
        btn_modificar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jtable_caja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtable_caja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_cajaMouseClicked(evt);
            }
        });
        jScrollPane_caja.setViewportView(jtable_caja);

        jl_ingreso.setBackground(new java.awt.Color(243, 243, 194));
        jl_ingreso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jl_ingreso.setForeground(new java.awt.Color(243, 243, 194));
        jl_ingreso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_ingreso.setText("Ingreso:");

        jl_monto.setBackground(new java.awt.Color(243, 243, 194));
        jl_monto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jl_monto.setForeground(new java.awt.Color(243, 243, 194));
        jl_monto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_monto.setText("Monto:");

        jl_especificacion.setBackground(new java.awt.Color(243, 243, 194));
        jl_especificacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jl_especificacion.setForeground(new java.awt.Color(243, 243, 194));
        jl_especificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_especificacion.setText("Especificacion:");

        jl_efectivo.setBackground(new java.awt.Color(243, 243, 194));
        jl_efectivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jl_efectivo.setForeground(new java.awt.Color(243, 243, 194));
        jl_efectivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_efectivo.setText("Efectivo:");

        jl_efectivoLabel.setBackground(new java.awt.Color(243, 243, 194));
        jl_efectivoLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jl_efectivoLabel.setForeground(new java.awt.Color(243, 243, 194));
        jl_efectivoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_efectivoLabel.setText("Efectivo:");

        jl_Total.setBackground(new java.awt.Color(243, 243, 194));
        jl_Total.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jl_Total.setForeground(new java.awt.Color(243, 243, 194));
        jl_Total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_Total.setText("Total:");

        btn_limpiar.setBackground(new java.awt.Color(255, 253, 118));
        btn_limpiar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_borrarRegistros.setBackground(new java.awt.Color(255, 253, 118));
        btn_borrarRegistros.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_borrarRegistros.setText("Borrar registros de caja");
        btn_borrarRegistros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_borrarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarRegistrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jl_efectivoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jl_ingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jl_monto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jl_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jl_especificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jr_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jr_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jt_especificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_borrarRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_especificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_especificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jr_ingreso)
                            .addComponent(jl_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jr_efectivo)
                            .addComponent(jl_efectivoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jl_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agregar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_borrarRegistros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_caja, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsFacu(){        
        this.getContentPane().setBackground(new Color(49,28,28));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Caja");
        jr_efectivo.setSelected(true);
        jr_ingreso.setSelected(true);
    }
    
    private boolean checkCampos(){
        return !(jt_monto.getText().equalsIgnoreCase(""));
    }
    
    private void calcularSaldos(){
        jl_Total.setText("Total: "+MovimientoBackEnd.calcularTotal() + " $");
        jl_efectivo.setText("Efectivo: "+MovimientoBackEnd.calcularEfectivo() + " $");   
    }
    
    private void limpiarCampos(){
        jt_monto.setText("");
        jt_especificacion.setText("");
        jr_ingreso.setSelected(true);
        jr_efectivo.setSelected(true);
    }
    
    //Metodo que actualiza los valores de la tabla segun la base de datos
    private void actualizarTabla(){
        jtable_caja.setModel(MovimientoBackEnd.actualizarTabla());
        calcularSaldos();
    }
    
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if(checkCampos()){
            Date date = new Date();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            
            MovimientoEntidad movimiento = new MovimientoEntidad(Float.valueOf(jt_monto.getText()),jt_especificacion.getText(), 
                jr_ingreso.isSelected(), jr_efectivo.isSelected(), simpleDateFormat.format(date));
            if(MovimientoBackEnd.agregarMovimiento(movimiento))
                JOptionPane.showMessageDialog(null, "Movimiento agregado con exito");
            else
                JOptionPane.showMessageDialog(null, "Error: al intentar agregar el movimiento");
            actualizarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "El monto es un campo obligatorio.");   
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (checkCampos()) {
            int row = jtable_caja.getSelectedRow(); 
            int id = Integer.valueOf(jtable_caja.getValueAt(row, 0).toString());
            if(MovimientoBackEnd.eliminarMovimiento(id))
                JOptionPane.showMessageDialog(null, "Venta eliminada con exito");
            else
                JOptionPane.showMessageDialog(null, "Error: al intentar eliminar la venta");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "El monto es un campo obligatorio");
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (checkCampos()) {
            Date date = new Date();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            MovimientoEntidad movimiento = new MovimientoEntidad(Float.valueOf(jt_monto.getText()),
                    jt_especificacion.getText(), jr_ingreso.isSelected()
                    ,jr_efectivo.isSelected(), simpleDateFormat.format(date));
            int row = jtable_caja.getSelectedRow();
            int id = Integer.valueOf(jtable_caja.getValueAt(row, 0).toString());
            
            if(MovimientoBackEnd.modificarMovimiento(movimiento, id))
                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            else
                JOptionPane.showMessageDialog(null, "Error: al intentar modificar el movimiento seleccionado");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "El monto es un campo obligatorio");
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void jtable_cajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_cajaMouseClicked
        int filaSelec = jtable_caja.rowAtPoint(evt.getPoint());
        jt_monto.setText(jtable_caja.getValueAt(filaSelec, 1).toString());
        jt_especificacion.setText(jtable_caja.getValueAt(filaSelec, 2).toString());
        jr_ingreso.setSelected(jtable_caja.getValueAt(filaSelec, 3).toString().equals("Ingreso"));
        jr_efectivo.setSelected(jtable_caja.getValueAt(filaSelec, 4).toString().equals("Efectivo"));
    }//GEN-LAST:event_jtable_cajaMouseClicked

    private void jt_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_montoKeyTyped
        char c = evt.getKeyChar();
        if ( (c != '.') && (c < '0' || c > '9'))
            evt.consume();
    }//GEN-LAST:event_jt_montoKeyTyped

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_borrarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarRegistrosActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Confirmar");
        if (result == JOptionPane.YES_OPTION) {
            if(MovimientoBackEnd.eliminarRegistros())
                JOptionPane.showMessageDialog(null, "Se borraron los registros hasta la fecha");
        }
        actualizarTabla();
    }//GEN-LAST:event_btn_borrarRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GestionCaja().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_borrarRegistros;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JScrollPane jScrollPane_caja;
    private javax.swing.JLabel jl_Total;
    private javax.swing.JLabel jl_efectivo;
    private javax.swing.JLabel jl_efectivoLabel;
    private javax.swing.JLabel jl_especificacion;
    private javax.swing.JLabel jl_ingreso;
    private javax.swing.JLabel jl_monto;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JRadioButton jr_efectivo;
    private javax.swing.JRadioButton jr_ingreso;
    private javax.swing.JTextField jt_especificacion;
    private javax.swing.JTextField jt_monto;
    private javax.swing.JTable jtable_caja;
    // End of variables declaration//GEN-END:variables
}
