/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ClienteBackEnd;
import java.awt.Color;
import BackEnd.PedidoBackEnd;
import BackEnd.ViandaBackEnd;
import javax.swing.JOptionPane;
/**
 *
 * @author facul
 */
public class PedidosJF extends javax.swing.JFrame {

    /**
     * Constructor: - Creates new form GestionClientes
     */
    public PedidosJF() {
        initComponents();
        this.getContentPane().setBackground(new Color(49,28,28));
        actualizarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jt_cliente = new javax.swing.JTextField();
        jt_vianda = new javax.swing.JTextField();
        jt_precio = new javax.swing.JTextField();
        jt_dias = new javax.swing.JTextField();
        btn_encargar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jtable_lunes = new javax.swing.JTable();
        jtable_martes = new javax.swing.JTable();
        jtable_miercoles_1 = new javax.swing.JTable();
        jtable_miercoles_2 = new javax.swing.JTable();
        jtable_jueves = new javax.swing.JTable();
        jtable_viernes = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_clientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_viandas = new javax.swing.JTable();
        jt_id = new javax.swing.JTextField();
        js_unidades = new javax.swing.JSpinner();
        jl_unidades1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 28, 28));

        jLabel1.setBackground(new java.awt.Color(49, 28, 28));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 253, 118));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEDIDOS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jt_cliente.setBackground(new java.awt.Color(243, 243, 194));
        jt_cliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_cliente.setText("Cliente:");
        jt_cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jt_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_clienteMouseClicked(evt);
            }
        });
        jt_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_clienteKeyReleased(evt);
            }
        });

        jt_vianda.setBackground(new java.awt.Color(243, 243, 194));
        jt_vianda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_vianda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_vianda.setText("Vianda:");
        jt_vianda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jt_vianda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_viandaMouseClicked(evt);
            }
        });
        jt_vianda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_viandaKeyReleased(evt);
            }
        });

        jt_precio.setEditable(false);
        jt_precio.setBackground(new java.awt.Color(243, 243, 194));
        jt_precio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_precio.setText("Precio:");
        jt_precio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jt_precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_precioMouseClicked(evt);
            }
        });
        jt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_precioKeyTyped(evt);
            }
        });

        jt_dias.setBackground(new java.awt.Color(243, 243, 194));
        jt_dias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_dias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_dias.setText("Dias:");
        jt_dias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jt_dias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_diasMouseClicked(evt);
            }
        });

        btn_encargar.setBackground(new java.awt.Color(255, 253, 118));
        btn_encargar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_encargar.setText("Encargar");
        btn_encargar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_encargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encargarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 253, 118));
        btn_cancelar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(255, 253, 118));
        btn_modificar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jtable_lunes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("Lunes", jtable_lunes);

        jtable_martes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("Martes", jtable_martes);

        jtable_miercoles_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("Miercoles1", jtable_miercoles_1);

        jtable_miercoles_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("Miercoles2", jtable_miercoles_2);

        jtable_jueves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("Jueves", jtable_jueves);

        jtable_viernes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("Viernes", jtable_viernes);

        jtable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtable_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_clientes);

        jTabbedPane1.addTab("Clientes", jScrollPane1);

        jtable_viandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtable_viandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_viandasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_viandas);

        jTabbedPane1.addTab("Viandas", jScrollPane2);

        jt_id.setBackground(new java.awt.Color(243, 243, 194));
        jt_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_id.setText("ID:");
        jt_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jt_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_idMouseClicked(evt);
            }
        });

        jl_unidades1.setBackground(new java.awt.Color(243, 243, 194));
        jl_unidades1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jl_unidades1.setForeground(new java.awt.Color(243, 243, 194));
        jl_unidades1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_unidades1.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_encargar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jt_dias, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                        .addComponent(jt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                        .addComponent(jt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jl_unidades1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jt_cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                                .addComponent(jt_vianda, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(js_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_unidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jt_vianda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(js_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btn_encargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo que limpia los valores de los campos de texto
    private void limpiarCampos(){
        jt_cliente.setText("Cliente:");
        jt_vianda.setText("Vianda:");
        jt_unidades.setText("Unidades:");
        jt_precio.setText("Precio:");
        jt_dias.setText("Dias:");
        jt_id.setText("ID");
    }
    
    //Metodo que chequea que ningun campo de texto este vacio.
    private boolean checkCampos(){
        return !(jt_cliente.getText().equalsIgnoreCase("") ||
                jt_vianda.getText().equalsIgnoreCase("") ||
                jt_unidades.getText().equalsIgnoreCase("") ||
                jt_precio.getText().equalsIgnoreCase("") ||
                jt_dias.getText().equalsIgnoreCase(""));
    }
    
    //Metodo que actualiza los valores de la tabla segun la base de datos
    private void actualizarTablas(){
        jtable_clientes.setModel(ClienteBackEnd.actualizarTabla());
        jtable_viandas.setModel(ViandaBackEnd.actualizarTabla());
        jtable_lunes.setModel(PedidoBackEnd.actualizarTabla("L"));
        jtable_lunes.setModel(PedidoBackEnd.actualizarTabla("MA"));
        jtable_lunes.setModel(PedidoBackEnd.actualizarTabla("M1"));
        jtable_lunes.setModel(PedidoBackEnd.actualizarTabla("J"));
        jtable_lunes.setModel(PedidoBackEnd.actualizarTabla("V"));
        jtable_lunes.setModel(PedidoBackEnd.actualizarTabla("M2"));
    }

    private void jt_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_clienteMouseClicked
        jt_cliente.setText("");
    }//GEN-LAST:event_jt_clienteMouseClicked

    private void jt_viandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_viandaMouseClicked
        jt_vianda.setText("");
    }//GEN-LAST:event_jt_viandaMouseClicked

    private void jt_precioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_precioMouseClicked
        jt_precio.setText("");
    }//GEN-LAST:event_jt_precioMouseClicked

    private void jt_diasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_diasMouseClicked
        jt_dias.setText("");
    }//GEN-LAST:event_jt_diasMouseClicked







    private void filtrarCliente(String nombre){
        jtable_clientes.setModel(ClienteBackEnd.filtrarNombre(nombre));
    }
    
    private void filtrarVianda(String vianda){
        jtable_viandas.setModel(ViandaBackEnd.filtrarNombre(vianda));
    }
    
    private void btn_encargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encargarActionPerformed
        if(checkCampos()){
            PedidoBackEnd pedido = new PedidoBackEnd(jt_cliente.getText(), jt_vianda.getText(),
                    Integer.valueOf(jt_unidades.getText()), Float.valueOf(jt_precio.getText()), jt_dias.getText(),0);
            PedidoBackEnd.agregarPedido(pedido);
            actualizarTablas();
        }else{
            JOptionPane.showMessageDialog(null, "Faltan campos de completar");
        }
    }//GEN-LAST:event_btn_encargarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        if(checkCampos()){
            JOptionPane.showMessageDialog(null, "Puede que falte completar algun campo");
        }else{
            int id = Integer.valueOf(jt_id.getText());
            PedidoBackEnd.cancelarPedido(id);
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    
    
    
    
    
    
    
    
    private void jt_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_idMouseClicked
        jt_id.setText("");
    }//GEN-LAST:event_jt_idMouseClicked

    private void jt_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_clienteKeyReleased
        this.filtrarCliente(jt_cliente.getText());
    }//GEN-LAST:event_jt_clienteKeyReleased

    private void jt_viandaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_viandaKeyReleased
        this.filtrarVianda(jt_vianda.getText());
    }//GEN-LAST:event_jt_viandaKeyReleased

    private void jt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_precioKeyTyped
        char c = evt.getKeyChar();
        if ( (c != '.') && (c < '0' || c > '9'))
            evt.consume();
    }//GEN-LAST:event_jt_precioKeyTyped

    private void jtable_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_clientesMouseClicked
        int filaSeleccionada = jtable_clientes.rowAtPoint(evt.getPoint());
        jt_cliente.setText(jtable_clientes.getValueAt(filaSeleccionada, 0).toString() + 
                " " + jtable_clientes.getValueAt(filaSeleccionada, 1).toString());
    }//GEN-LAST:event_jtable_clientesMouseClicked

    private void jtable_viandasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_viandasMouseClicked
        int filaSeleccionada = jtable_viandas.rowAtPoint(evt.getPoint());
        jt_vianda.setText(jtable_viandas.getValueAt(filaSeleccionada, 1).toString());
        jt_precio.setText(jtable_viandas.getValueAt(filaSeleccionada, 2).toString());
        jt_dias.setText(jtable_viandas.getValueAt(filaSeleccionada, 3).toString());
    }//GEN-LAST:event_jtable_viandasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PedidosJF().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_encargar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jl_unidades1;
    private javax.swing.JSpinner js_unidades;
    private javax.swing.JTextField jt_cliente;
    private javax.swing.JTextField jt_dias;
    private javax.swing.JTextField jt_id;
    private javax.swing.JTextField jt_precio;
    private javax.swing.JTextField jt_vianda;
    private javax.swing.JTable jtable_clientes;
    private javax.swing.JTable jtable_jueves;
    private javax.swing.JTable jtable_lunes;
    private javax.swing.JTable jtable_martes;
    private javax.swing.JTable jtable_miercoles_1;
    private javax.swing.JTable jtable_miercoles_2;
    private javax.swing.JTable jtable_viandas;
    private javax.swing.JTable jtable_viernes;
    // End of variables declaration//GEN-END:variables
}
