/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.MovimientoBackEnd;
import BackEnd.PedidoBackEnd;
import BackEnd.VentaBackEnd;
import Entidad.MovimientoEntidad;
import Entidad.TipoComida;
import Entidad.VentaEntidad;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author facul
 */
public class VentasJF extends javax.swing.JFrame {

    /**
     * Constructor: - Creates new form GestionClientes
     */
    public VentasJF() {
        initComponents();
        initComponentsFacu();
        actualizarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        viandas = new javax.swing.JLabel();
        unidades = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        jt_unidades = new javax.swing.JTextField();
        jt_cliente = new javax.swing.JTextField();
        jt_vianda = new javax.swing.JTextField();
        jt_precio = new javax.swing.JTextField();
        jt_id = new javax.swing.JTextField();
        btn_vender = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        tipo = new javax.swing.JLabel();
        jt_tipoComida = new javax.swing.JTextField();
        btn_borrarVentas = new javax.swing.JButton();
        efectivo = new javax.swing.JLabel();
        jcheck_efectivo = new javax.swing.JCheckBox();
        jscrollPane_ventas = new javax.swing.JScrollPane();
        jtable_ventas = new javax.swing.JTable();
        jtab_panel_general = new javax.swing.JTabbedPane();
        jtable_lunes = new javax.swing.JTable();
        jtable_martes = new javax.swing.JTable();
        jtable_miercoles_carne = new javax.swing.JTable();
        jtable_miercoles_pescado = new javax.swing.JTable();
        jtable_jueves = new javax.swing.JTable();
        jtable_viernes = new javax.swing.JTable();
        btn_vender2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 28, 28));

        titulo.setBackground(new java.awt.Color(49, 28, 28));
        titulo.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 253, 118));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("VENTAS");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        viandas.setBackground(new java.awt.Color(243, 243, 194));
        viandas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        viandas.setForeground(new java.awt.Color(243, 243, 194));
        viandas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viandas.setText("Vianda:");

        unidades.setBackground(new java.awt.Color(243, 243, 194));
        unidades.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        unidades.setForeground(new java.awt.Color(243, 243, 194));
        unidades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        unidades.setText("Unidades:");

        id.setBackground(new java.awt.Color(243, 243, 194));
        id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(243, 243, 194));
        id.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        id.setText("ID:");

        precio.setBackground(new java.awt.Color(243, 243, 194));
        precio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        precio.setForeground(new java.awt.Color(243, 243, 194));
        precio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        precio.setText("Precio:");

        cliente.setBackground(new java.awt.Color(243, 243, 194));
        cliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cliente.setForeground(new java.awt.Color(243, 243, 194));
        cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cliente.setText("Cliente:");

        jt_unidades.setEditable(false);
        jt_unidades.setBackground(new java.awt.Color(243, 243, 194));
        jt_unidades.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_unidades.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_unidades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jt_cliente.setBackground(new java.awt.Color(243, 243, 194));
        jt_cliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jt_vianda.setBackground(new java.awt.Color(243, 243, 194));
        jt_vianda.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_vianda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_vianda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jt_precio.setBackground(new java.awt.Color(243, 243, 194));
        jt_precio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_precio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jt_id.setBackground(new java.awt.Color(243, 243, 194));
        jt_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        btn_vender.setBackground(new java.awt.Color(255, 253, 118));
        btn_vender.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_vender.setText("Vender");
        btn_vender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_venderActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 253, 118));
        btn_eliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(255, 253, 118));
        btn_modificar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        tipo.setBackground(new java.awt.Color(243, 243, 194));
        tipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo.setForeground(new java.awt.Color(243, 243, 194));
        tipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipo.setText("Tipo:");

        jt_tipoComida.setBackground(new java.awt.Color(243, 243, 194));
        jt_tipoComida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_tipoComida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_tipoComida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        btn_borrarVentas.setBackground(new java.awt.Color(255, 253, 118));
        btn_borrarVentas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_borrarVentas.setText("Borrar registro de ventas");
        btn_borrarVentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_borrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarVentasActionPerformed(evt);
            }
        });

        efectivo.setBackground(new java.awt.Color(243, 243, 194));
        efectivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        efectivo.setForeground(new java.awt.Color(243, 243, 194));
        efectivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        efectivo.setText("Efectivo:");

        jtable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jscrollPane_ventas.setViewportView(jtable_ventas);

        jtable_lunes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_lunes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_lunesMouseClicked(evt);
            }
        });
        jtab_panel_general.addTab("Lunes", jtable_lunes);

        jtable_martes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_martes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_martesMouseClicked(evt);
            }
        });
        jtab_panel_general.addTab("Martes", jtable_martes);

        jtable_miercoles_carne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_miercoles_carne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_miercoles_carneMouseClicked(evt);
            }
        });
        jtab_panel_general.addTab("Miercoles Carne", jtable_miercoles_carne);

        jtable_miercoles_pescado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_miercoles_pescado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_miercoles_pescadoMouseClicked(evt);
            }
        });
        jtab_panel_general.addTab("Miercoles Pescado", jtable_miercoles_pescado);

        jtable_jueves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_jueves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_juevesMouseClicked(evt);
            }
        });
        jtab_panel_general.addTab("Jueves", jtable_jueves);

        jtable_viernes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_viernes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_viernesMouseClicked(evt);
            }
        });
        jtab_panel_general.addTab("Viernes", jtable_viernes);

        btn_vender2.setBackground(new java.awt.Color(255, 253, 118));
        btn_vender2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_vender2.setText("Limpiar");
        btn_vender2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btn_vender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vender2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viandas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jt_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(jt_vianda, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jt_unidades, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jt_precio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jt_id, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcheck_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jt_tipoComida)
                                                .addGap(12, 12, 12))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jscrollPane_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                            .addComponent(jtab_panel_general, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_vender2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_borrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_vender)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_vender2)
                            .addComponent(btn_borrarVentas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jt_vianda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jt_tipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(efectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcheck_efectivo)))
                            .addComponent(jscrollPane_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jtab_panel_general, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsFacu() {
        this.getContentPane().setBackground(new Color(49, 28, 28));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setTitle("Ventas");
    }

    private void limpiarCampos() {
        jt_cliente.setText("");
        jt_vianda.setText("");
        jt_unidades.setText("");
        jt_precio.setText("");
        jt_id.setText("");
        jt_tipoComida.setText("");
        actualizarTablas();
    }

    private boolean checkCampos() {
        return !(jt_cliente.getText().equalsIgnoreCase("")
                || jt_vianda.getText().equalsIgnoreCase("")
                || jt_unidades.getText().equalsIgnoreCase("")
                || jt_precio.getText().equalsIgnoreCase("")
                || jt_id.getText().equalsIgnoreCase(""));
    }

    private void actualizarTablas() {
        jtable_lunes.setModel(PedidoBackEnd.actualizarTablas("Lunes"));
        jtable_martes.setModel(PedidoBackEnd.actualizarTablas("Martes"));
        jtable_miercoles_carne.setModel(PedidoBackEnd.actualizarTablas("MiercolesC"));
        jtable_miercoles_pescado.setModel(PedidoBackEnd.actualizarTablas("MiercolesP"));
        jtable_jueves.setModel(PedidoBackEnd.actualizarTablas("Jueves"));
        jtable_viernes.setModel(PedidoBackEnd.actualizarTablas("Viernes"));
        jtable_ventas.setModel(VentaBackEnd.actualizarTable());
    }

    private void btn_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_venderActionPerformed
        if (checkCampos()) {
            Date date = new Date();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

            VentaEntidad venta = new VentaEntidad(jt_cliente.getText(), jt_vianda.getText(),
                    Integer.valueOf(jt_unidades.getText()), Float.valueOf(jt_precio.getText()),
                    simpleDateFormat.format(date), Integer.valueOf(jt_id.getText()),
                    TipoComida.valueOf(jt_tipoComida.getText()));
            MovimientoEntidad movimiento = new MovimientoEntidad(Float.valueOf(jt_precio.getText()),
                    jt_vianda.getText(), true, jcheck_efectivo.isSelected(), simpleDateFormat.format(date));

            boolean flagVenta = VentaBackEnd.agregarVenta(venta);
            boolean flagPedido = PedidoBackEnd.eliminarPedido(venta.getId());
            boolean flagMovimiento = MovimientoBackEnd.agregarMovimiento(movimiento);

            if (flagVenta && flagPedido && flagMovimiento) {
                JOptionPane.showMessageDialog(null, "Venta agregada con exito");
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al intentar agregar la venta del pedido seleccionado");
            }

            actualizarTablas();
        } else {
            JOptionPane.showMessageDialog(null, "Error: Campos incompletos.");
        }
    }//GEN-LAST:event_btn_venderActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (checkCampos()) {
            int id = Integer.valueOf(jt_id.getText());
            if (VentaBackEnd.eliminarVenta(id)) {
                JOptionPane.showMessageDialog(null, "Venta eliminada con exito");
            } else {
                JOptionPane.showMessageDialog(null, "Error al intentar eliminar la venta.");
            }
            actualizarTablas();
        } else
            JOptionPane.showMessageDialog(null, "Error al intentar eliminar la venta");
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (checkCampos()) {
            Date date = new Date();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            VentaEntidad venta = new VentaEntidad(jt_cliente.getText(), jt_vianda.getText(), Integer.valueOf(jt_unidades.getText()),
                    Float.valueOf(jt_precio.getText()), simpleDateFormat.format(date), Integer.valueOf(jt_id.getText()), TipoComida.valueOf(jt_tipoComida.getText()));
            if (VentaBackEnd.modificarVenta(venta)) {
                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            } else {
                JOptionPane.showMessageDialog(null, "Error: al intentar modificar la venta seleccionada");
            }
            actualizarTablas();
        } else {
            JOptionPane.showMessageDialog(null, "Modificacion exitosa");
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_borrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarVentasActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Confirmar");
        if (result == JOptionPane.YES_OPTION) {
            if(VentaBackEnd.eliminarRegistros())
                JOptionPane.showMessageDialog(null, "Se borraron los registros hasta la fecha");
        }
        actualizarTablas();
    }//GEN-LAST:event_btn_borrarVentasActionPerformed

    private void mouseClickFacu(JTable tabla, int filaSeleccionada) {
        jt_id.setText(tabla.getValueAt(filaSeleccionada, 0).toString());
        jt_cliente.setText(tabla.getValueAt(filaSeleccionada, 1).toString());
        jt_vianda.setText(tabla.getValueAt(filaSeleccionada, 2).toString());
        jt_unidades.setText(tabla.getValueAt(filaSeleccionada, 3).toString());
        jt_precio.setText(tabla.getValueAt(filaSeleccionada, 4).toString());
        jt_tipoComida.setText(tabla.getValueAt(filaSeleccionada, 6).toString());                    
    }

    private void jtable_lunesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_lunesMouseClicked
        int filaSeleccionada = jtable_lunes.rowAtPoint(evt.getPoint());
        mouseClickFacu((JTable) jtab_panel_general.getSelectedComponent(), filaSeleccionada);
    }//GEN-LAST:event_jtable_lunesMouseClicked

    private void jtable_martesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_martesMouseClicked
        int filaSeleccionada = jtable_martes.getSelectedRow();
        mouseClickFacu((JTable) jtab_panel_general.getSelectedComponent(), filaSeleccionada);
    }//GEN-LAST:event_jtable_martesMouseClicked

    private void jtable_miercoles_carneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_miercoles_carneMouseClicked
        int filaSeleccionada = jtable_miercoles_carne.getSelectedRow();
        mouseClickFacu((JTable) jtab_panel_general.getSelectedComponent(), filaSeleccionada);
    }//GEN-LAST:event_jtable_miercoles_carneMouseClicked

    private void jtable_miercoles_pescadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_miercoles_pescadoMouseClicked
        int filaSeleccionada = jtable_miercoles_pescado.getSelectedRow();
        mouseClickFacu((JTable) jtab_panel_general.getSelectedComponent(), filaSeleccionada);
    }//GEN-LAST:event_jtable_miercoles_pescadoMouseClicked

    private void jtable_juevesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_juevesMouseClicked
        int filaSeleccionada = jtable_jueves.getSelectedRow();
        mouseClickFacu((JTable) jtab_panel_general.getSelectedComponent(), filaSeleccionada);
    }//GEN-LAST:event_jtable_juevesMouseClicked

    private void btn_vender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vender2ActionPerformed
        jt_cliente.setText("");
        jt_vianda.setText("");
        jt_unidades.setText("");
        jt_precio.setText("");
        jt_id.setText("");
        jt_tipoComida.setText("");
        jcheck_efectivo.setSelected(false);
    }//GEN-LAST:event_btn_vender2ActionPerformed

    private void jtable_viernesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_viernesMouseClicked
        int filaSeleccionada = jtable_viernes.getSelectedRow();
        mouseClickFacu((JTable) jtab_panel_general.getSelectedComponent(), filaSeleccionada);
    }//GEN-LAST:event_jtable_viernesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentasJF().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrarVentas;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_vender;
    private javax.swing.JButton btn_vender2;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel efectivo;
    private javax.swing.JLabel id;
    private javax.swing.JCheckBox jcheck_efectivo;
    private javax.swing.JScrollPane jscrollPane_ventas;
    private javax.swing.JTextField jt_cliente;
    private javax.swing.JTextField jt_id;
    private javax.swing.JTextField jt_precio;
    private javax.swing.JTextField jt_tipoComida;
    private javax.swing.JTextField jt_unidades;
    private javax.swing.JTextField jt_vianda;
    private javax.swing.JTabbedPane jtab_panel_general;
    private javax.swing.JTable jtable_jueves;
    private javax.swing.JTable jtable_lunes;
    private javax.swing.JTable jtable_martes;
    private javax.swing.JTable jtable_miercoles_carne;
    private javax.swing.JTable jtable_miercoles_pescado;
    private javax.swing.JTable jtable_ventas;
    private javax.swing.JTable jtable_viernes;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel unidades;
    private javax.swing.JLabel viandas;
    // End of variables declaration//GEN-END:variables
}
